name: issues_workflow
on:
  issues:
    types:[opened]
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump context"
      - run: ${{toJSON(github.event)}} | jq
      - shell: bash
      
    
